package com.rca.immatriculation.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Activite implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.lang.String actCode;
	private java.lang.String actLibelle;

	public Activite() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getActCode() {
		return this.actCode;
	}

	public void setActCode(java.lang.String actCode) {
		this.actCode = actCode;
	}

	public java.lang.String getActLibelle() {
		return this.actLibelle;
	}

	public void setActLibelle(java.lang.String actLibelle) {
		this.actLibelle = actLibelle;
	}

	public Activite(java.lang.Long id, java.lang.String actCode,
			java.lang.String actLibelle) {
		this.id = id;
		this.actCode = actCode;
		this.actLibelle = actLibelle;
	}

}