package com.rca.immatriculation.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Contribuable implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.util.List<com.rca.immatriculation.model.StatutDemande> statutDemande;
	private com.rca.immatriculation.model.InfoGeneral infoGeneral;
	private com.rca.immatriculation.model.TypePersonne ctbTypePers;
	private com.rca.immatriculation.model.FormeJuridique frmJ;
	private com.rca.immatriculation.model.Activite actPrincipal;
	private com.rca.immatriculation.model.Activite actSecond;
	private com.rca.immatriculation.model.InfoFinance infoFin;
	private java.util.List<com.rca.immatriculation.model.Entite> entite;
	private java.util.List<com.rca.immatriculation.model.Statut> statut;
	private Quartier quartier;
	private com.rca.immatriculation.model.Service service;

	public Contribuable() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.util.List<com.rca.immatriculation.model.StatutDemande> getStatutDemande() {
		return this.statutDemande;
	}

	public void setStatutDemande(
			java.util.List<com.rca.immatriculation.model.StatutDemande> statutDemande) {
		this.statutDemande = statutDemande;
	}

	public com.rca.immatriculation.model.InfoGeneral getInfoGeneral() {
		return this.infoGeneral;
	}

	public void setInfoGeneral(
			com.rca.immatriculation.model.InfoGeneral infoGeneral) {
		this.infoGeneral = infoGeneral;
	}

	public com.rca.immatriculation.model.TypePersonne getCtbTypePers() {
		return this.ctbTypePers;
	}

	public void setCtbTypePers(
			com.rca.immatriculation.model.TypePersonne ctbTypePers) {
		this.ctbTypePers = ctbTypePers;
	}

	public com.rca.immatriculation.model.FormeJuridique getFrmJ() {
		return this.frmJ;
	}

	public void setFrmJ(com.rca.immatriculation.model.FormeJuridique frmJ) {
		this.frmJ = frmJ;
	}

	public com.rca.immatriculation.model.Activite getActPrincipal() {
		return this.actPrincipal;
	}

	public void setActPrincipal(
			com.rca.immatriculation.model.Activite actPrincipal) {
		this.actPrincipal = actPrincipal;
	}

	public com.rca.immatriculation.model.Activite getActSecond() {
		return this.actSecond;
	}

	public void setActSecond(com.rca.immatriculation.model.Activite actSecond) {
		this.actSecond = actSecond;
	}

	public com.rca.immatriculation.model.InfoFinance getInfoFin() {
		return this.infoFin;
	}

	public void setInfoFin(com.rca.immatriculation.model.InfoFinance infoFin) {
		this.infoFin = infoFin;
	}

	public java.util.List<com.rca.immatriculation.model.Entite> getEntite() {
		return this.entite;
	}

	public void setEntite(
			java.util.List<com.rca.immatriculation.model.Entite> entite) {
		this.entite = entite;
	}

	public java.util.List<com.rca.immatriculation.model.Statut> getStatut() {
		return this.statut;
	}

	public void setStatut(
			java.util.List<com.rca.immatriculation.model.Statut> statut) {
		this.statut = statut;
	}

	public com.rca.immatriculation.model.Service getService() {
		return this.service;
	}

	public void setService(com.rca.immatriculation.model.Service service) {
		this.service = service;
	}

	public com.rca.immatriculation.model.Quartier getQuartier() {
		return this.quartier;
	}

	public void setQuartier(com.rca.immatriculation.model.Quartier quartier) {
		this.quartier = quartier;
	}

	public Contribuable(
			java.lang.Long id,
			java.util.List<com.rca.immatriculation.model.StatutDemande> statutDemande,
			com.rca.immatriculation.model.InfoGeneral infoGeneral,
			com.rca.immatriculation.model.TypePersonne ctbTypePers,
			com.rca.immatriculation.model.FormeJuridique frmJ,
			com.rca.immatriculation.model.Activite actPrincipal,
			com.rca.immatriculation.model.Activite actSecond,
			com.rca.immatriculation.model.InfoFinance infoFin,
			java.util.List<com.rca.immatriculation.model.Entite> entite,
			java.util.List<com.rca.immatriculation.model.Statut> statut,
			com.rca.immatriculation.model.Quartier quartier,
			com.rca.immatriculation.model.Service service) {
		this.id = id;
		this.statutDemande = statutDemande;
		this.infoGeneral = infoGeneral;
		this.ctbTypePers = ctbTypePers;
		this.frmJ = frmJ;
		this.actPrincipal = actPrincipal;
		this.actSecond = actSecond;
		this.infoFin = infoFin;
		this.entite = entite;
		this.statut = statut;
		this.quartier = quartier;
		this.service = service;
	}

}