package com.rca.immatriculation.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Direction implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.lang.String dirCode;
	private java.lang.String dirLibelle;

	public Direction() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getDirCode() {
		return this.dirCode;
	}

	public void setDirCode(java.lang.String dirCode) {
		this.dirCode = dirCode;
	}

	public java.lang.String getDirLibelle() {
		return this.dirLibelle;
	}

	public void setDirLibelle(java.lang.String dirLibelle) {
		this.dirLibelle = dirLibelle;
	}

	public Direction(java.lang.Long id, java.lang.String dirCode,
			java.lang.String dirLibelle) {
		this.id = id;
		this.dirCode = dirCode;
		this.dirLibelle = dirLibelle;
	}

}