package com.rca.immatriculation.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Entite implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.lang.String numEnreg;
	private java.lang.String nom;
	private java.lang.String prenom;
	private java.util.Date dateNaiss;
	private com.rca.immatriculation.model.TypeIdentite typeIdentite;
	private com.rca.immatriculation.model.Nationalite nationalite;
	private java.lang.String profession;
	private java.lang.String nomPere;
	private java.lang.String nomMere;
	private java.lang.String numPieceIdentite;
	private java.lang.String numCarteSejour;
	private java.lang.String nombreEnfant;
	private java.lang.String boitePostale;
	private java.lang.String telephone;
	private java.lang.String fax;
	private java.lang.String courriel;

	public Entite() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getNumEnreg() {
		return this.numEnreg;
	}

	public void setNumEnreg(java.lang.String numEnreg) {
		this.numEnreg = numEnreg;
	}

	public java.lang.String getNom() {
		return this.nom;
	}

	public void setNom(java.lang.String nom) {
		this.nom = nom;
	}

	public java.lang.String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(java.lang.String prenom) {
		this.prenom = prenom;
	}

	public java.util.Date getDateNaiss() {
		return this.dateNaiss;
	}

	public void setDateNaiss(java.util.Date dateNaiss) {
		this.dateNaiss = dateNaiss;
	}

	public com.rca.immatriculation.model.TypeIdentite getTypeIdentite() {
		return this.typeIdentite;
	}

	public void setTypeIdentite(
			com.rca.immatriculation.model.TypeIdentite typeIdentite) {
		this.typeIdentite = typeIdentite;
	}

	public com.rca.immatriculation.model.Nationalite getNationalite() {
		return this.nationalite;
	}

	public void setNationalite(
			com.rca.immatriculation.model.Nationalite nationalite) {
		this.nationalite = nationalite;
	}

	public java.lang.String getProfession() {
		return this.profession;
	}

	public void setProfession(java.lang.String profession) {
		this.profession = profession;
	}

	public java.lang.String getNomPere() {
		return this.nomPere;
	}

	public void setNomPere(java.lang.String nomPere) {
		this.nomPere = nomPere;
	}

	public java.lang.String getNomMere() {
		return this.nomMere;
	}

	public void setNomMere(java.lang.String nomMere) {
		this.nomMere = nomMere;
	}

	public java.lang.String getNumPieceIdentite() {
		return this.numPieceIdentite;
	}

	public void setNumPieceIdentite(java.lang.String numPieceIdentite) {
		this.numPieceIdentite = numPieceIdentite;
	}

	public java.lang.String getNumCarteSejour() {
		return this.numCarteSejour;
	}

	public void setNumCarteSejour(java.lang.String numCarteSejour) {
		this.numCarteSejour = numCarteSejour;
	}

	public java.lang.String getNombreEnfant() {
		return this.nombreEnfant;
	}

	public void setNombreEnfant(java.lang.String nombreEnfant) {
		this.nombreEnfant = nombreEnfant;
	}

	public java.lang.String getBoitePostale() {
		return this.boitePostale;
	}

	public void setBoitePostale(java.lang.String boitePostale) {
		this.boitePostale = boitePostale;
	}

	public java.lang.String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(java.lang.String telephone) {
		this.telephone = telephone;
	}

	public java.lang.String getFax() {
		return this.fax;
	}

	public void setFax(java.lang.String fax) {
		this.fax = fax;
	}

	public java.lang.String getCourriel() {
		return this.courriel;
	}

	public void setCourriel(java.lang.String courriel) {
		this.courriel = courriel;
	}

	public Entite(java.lang.Long id, java.lang.String numEnreg,
			java.lang.String nom, java.lang.String prenom,
			java.util.Date dateNaiss,
			com.rca.immatriculation.model.TypeIdentite typeIdentite,
			com.rca.immatriculation.model.Nationalite nationalite,
			java.lang.String profession, java.lang.String nomPere,
			java.lang.String nomMere, java.lang.String numPieceIdentite,
			java.lang.String numCarteSejour, java.lang.String nombreEnfant,
			java.lang.String boitePostale, java.lang.String telephone,
			java.lang.String fax, java.lang.String courriel) {
		this.id = id;
		this.numEnreg = numEnreg;
		this.nom = nom;
		this.prenom = prenom;
		this.dateNaiss = dateNaiss;
		this.typeIdentite = typeIdentite;
		this.nationalite = nationalite;
		this.profession = profession;
		this.nomPere = nomPere;
		this.nomMere = nomMere;
		this.numPieceIdentite = numPieceIdentite;
		this.numCarteSejour = numCarteSejour;
		this.nombreEnfant = nombreEnfant;
		this.boitePostale = boitePostale;
		this.telephone = telephone;
		this.fax = fax;
		this.courriel = courriel;
	}

}