package com.rca.immatriculation.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Etat implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.lang.String etatCode;
	private java.lang.String etatLibelle;

	public Etat() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getEtatCode() {
		return this.etatCode;
	}

	public void setEtatCode(java.lang.String etatCode) {
		this.etatCode = etatCode;
	}

	public java.lang.String getEtatLibelle() {
		return this.etatLibelle;
	}

	public void setEtatLibelle(java.lang.String etatLibelle) {
		this.etatLibelle = etatLibelle;
	}

	public Etat(java.lang.Long id, java.lang.String etatCode,
			java.lang.String etatLibelle) {
		this.id = id;
		this.etatCode = etatCode;
		this.etatLibelle = etatLibelle;
	}

}