package com.rca.immatriculation.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FormeJuridique implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.lang.String frjCode;
	private java.lang.String frjLibelle;

	public FormeJuridique() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getFrjCode() {
		return this.frjCode;
	}

	public void setFrjCode(java.lang.String frjCode) {
		this.frjCode = frjCode;
	}

	public java.lang.String getFrjLibelle() {
		return this.frjLibelle;
	}

	public void setFrjLibelle(java.lang.String frjLibelle) {
		this.frjLibelle = frjLibelle;
	}

	public FormeJuridique(java.lang.Long id, java.lang.String frjCode,
			java.lang.String frjLibelle) {
		this.id = id;
		this.frjCode = frjCode;
		this.frjLibelle = frjLibelle;
	}

}