package com.rca.immatriculation.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InfoFinance implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.lang.String capital;
	private float pourcNatPublic;
	private float pourcEtrangerPublic;
	private float pourcNatPriv;
	private float chiffreAffPrev;
	private float numCompte;
	private com.rca.immatriculation.model.Banque banque;
	private com.rca.immatriculation.model.Direction direction;

	public InfoFinance() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getCapital() {
		return this.capital;
	}

	public void setCapital(java.lang.String capital) {
		this.capital = capital;
	}

	public float getPourcNatPublic() {
		return this.pourcNatPublic;
	}

	public void setPourcNatPublic(float pourcNatPublic) {
		this.pourcNatPublic = pourcNatPublic;
	}

	public float getPourcEtrangerPublic() {
		return this.pourcEtrangerPublic;
	}

	public void setPourcEtrangerPublic(float pourcEtrangerPublic) {
		this.pourcEtrangerPublic = pourcEtrangerPublic;
	}

	public float getPourcNatPriv() {
		return this.pourcNatPriv;
	}

	public void setPourcNatPriv(float pourcNatPriv) {
		this.pourcNatPriv = pourcNatPriv;
	}

	public float getChiffreAffPrev() {
		return this.chiffreAffPrev;
	}

	public void setChiffreAffPrev(float chiffreAffPrev) {
		this.chiffreAffPrev = chiffreAffPrev;
	}

	public float getNumCompte() {
		return this.numCompte;
	}

	public void setNumCompte(float numCompte) {
		this.numCompte = numCompte;
	}

	public com.rca.immatriculation.model.Banque getBanque() {
		return this.banque;
	}

	public void setBanque(com.rca.immatriculation.model.Banque banque) {
		this.banque = banque;
	}

	public com.rca.immatriculation.model.Direction getDirection() {
		return this.direction;
	}

	public void setDirection(com.rca.immatriculation.model.Direction direction) {
		this.direction = direction;
	}

	public InfoFinance(java.lang.Long id, java.lang.String capital,
			float pourcNatPublic, float pourcEtrangerPublic,
			float pourcNatPriv, float chiffreAffPrev, float numCompte,
			com.rca.immatriculation.model.Banque banque,
			com.rca.immatriculation.model.Direction direction) {
		this.id = id;
		this.capital = capital;
		this.pourcNatPublic = pourcNatPublic;
		this.pourcEtrangerPublic = pourcEtrangerPublic;
		this.pourcNatPriv = pourcNatPriv;
		this.chiffreAffPrev = chiffreAffPrev;
		this.numCompte = numCompte;
		this.banque = banque;
		this.direction = direction;
	}

}