package com.rca.immatriculation.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Nationalite implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.lang.String natCode;
	private java.lang.String natLibelle;

	public Nationalite() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getNatCode() {
		return this.natCode;
	}

	public void setNatCode(java.lang.String natCode) {
		this.natCode = natCode;
	}

	public java.lang.String getNatLibelle() {
		return this.natLibelle;
	}

	public void setNatLibelle(java.lang.String natLibelle) {
		this.natLibelle = natLibelle;
	}

	public Nationalite(java.lang.Long id, java.lang.String natCode,
			java.lang.String natLibelle) {
		this.id = id;
		this.natCode = natCode;
		this.natLibelle = natLibelle;
	}

}