package com.rca.immatriculation.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Prefecture implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.lang.String prfCode;
	private java.lang.String prfLibelle;

	public Prefecture() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getPrfCode() {
		return this.prfCode;
	}

	public void setPrfCode(java.lang.String prfCode) {
		this.prfCode = prfCode;
	}

	public java.lang.String getPrfLibelle() {
		return this.prfLibelle;
	}

	public void setPrfLibelle(java.lang.String prfLibelle) {
		this.prfLibelle = prfLibelle;
	}

	public Prefecture(java.lang.Long id, java.lang.String prfCode,
			java.lang.String prfLibelle) {
		this.id = id;
		this.prfCode = prfCode;
		this.prfLibelle = prfLibelle;
	}

}