package com.rca.immatriculation.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Quartier implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private com.rca.immatriculation.model.Commune commune;
	private java.lang.String qtrCode;
	private java.lang.String qtrLibelle;

	public Quartier() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public com.rca.immatriculation.model.Commune getCommune() {
		return this.commune;
	}

	public void setCommune(com.rca.immatriculation.model.Commune commune) {
		this.commune = commune;
	}

	public java.lang.String getQtrCode() {
		return this.qtrCode;
	}

	public void setQtrCode(java.lang.String qtrCode) {
		this.qtrCode = qtrCode;
	}

	public java.lang.String getQtrLibelle() {
		return this.qtrLibelle;
	}

	public void setQtrLibelle(java.lang.String qtrLibelle) {
		this.qtrLibelle = qtrLibelle;
	}

	public Quartier(java.lang.Long id,
			com.rca.immatriculation.model.Commune commune,
			java.lang.String qtrCode, java.lang.String qtrLibelle) {
		this.id = id;
		this.commune = commune;
		this.qtrCode = qtrCode;
		this.qtrLibelle = qtrLibelle;
	}

}