package com.rca.immatriculation.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Service implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private com.rca.immatriculation.model.Direction direction;
	private java.lang.String sceCode;
	private java.lang.String sceLibelle;

	public Service() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public com.rca.immatriculation.model.Direction getDirection() {
		return this.direction;
	}

	public void setDirection(com.rca.immatriculation.model.Direction direction) {
		this.direction = direction;
	}

	public java.lang.String getSceCode() {
		return this.sceCode;
	}

	public void setSceCode(java.lang.String sceCode) {
		this.sceCode = sceCode;
	}

	public java.lang.String getSceLibelle() {
		return this.sceLibelle;
	}

	public void setSceLibelle(java.lang.String sceLibelle) {
		this.sceLibelle = sceLibelle;
	}

	public Service(java.lang.Long id,
			com.rca.immatriculation.model.Direction direction,
			java.lang.String sceCode, java.lang.String sceLibelle) {
		this.id = id;
		this.direction = direction;
		this.sceCode = sceCode;
		this.sceLibelle = sceLibelle;
	}

}