package com.rca.immatriculation.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SousPrefecture implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private com.rca.immatriculation.model.Prefecture prefecture;
	private java.lang.String sprCode;
	private java.lang.String sprLibelle;

	public SousPrefecture() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public com.rca.immatriculation.model.Prefecture getPrefecture() {
		return this.prefecture;
	}

	public void setPrefecture(
			com.rca.immatriculation.model.Prefecture prefecture) {
		this.prefecture = prefecture;
	}

	public java.lang.String getSprCode() {
		return this.sprCode;
	}

	public void setSprCode(java.lang.String sprCode) {
		this.sprCode = sprCode;
	}

	public java.lang.String getSprLibelle() {
		return this.sprLibelle;
	}

	public void setSprLibelle(java.lang.String sprLibelle) {
		this.sprLibelle = sprLibelle;
	}

	public SousPrefecture(java.lang.Long id,
			com.rca.immatriculation.model.Prefecture prefecture,
			java.lang.String sprCode, java.lang.String sprLibelle) {
		this.id = id;
		this.prefecture = prefecture;
		this.sprCode = sprCode;
		this.sprLibelle = sprLibelle;
	}

}