package com.rca.immatriculation.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StatutDemande implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.lang.String statutDmdCode;
	private java.lang.String statutDmdLibelle;

	public StatutDemande() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getStatutDmdCode() {
		return this.statutDmdCode;
	}

	public void setStatutDmdCode(java.lang.String statutDmdCode) {
		this.statutDmdCode = statutDmdCode;
	}

	public java.lang.String getStatutDmdLibelle() {
		return this.statutDmdLibelle;
	}

	public void setStatutDmdLibelle(java.lang.String statutDmdLibelle) {
		this.statutDmdLibelle = statutDmdLibelle;
	}

	public StatutDemande(java.lang.Long id, java.lang.String statutDmdCode,
			java.lang.String statutDmdLibelle) {
		this.id = id;
		this.statutDmdCode = statutDmdCode;
		this.statutDmdLibelle = statutDmdLibelle;
	}

}