package com.rca.immatriculation.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Statut implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.lang.String statutCode;
	private java.lang.String statutLibelle;
	private java.util.Date dateDebut;
	private java.util.Date dateFin;
	private com.rca.immatriculation.model.Etat etat;

	public Statut() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getStatutCode() {
		return this.statutCode;
	}

	public void setStatutCode(java.lang.String statutCode) {
		this.statutCode = statutCode;
	}

	public java.lang.String getStatutLibelle() {
		return this.statutLibelle;
	}

	public void setStatutLibelle(java.lang.String statutLibelle) {
		this.statutLibelle = statutLibelle;
	}

	public java.util.Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(java.util.Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	public java.util.Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(java.util.Date dateFin) {
		this.dateFin = dateFin;
	}

	public com.rca.immatriculation.model.Etat getEtat() {
		return this.etat;
	}

	public void setEtat(com.rca.immatriculation.model.Etat etat) {
		this.etat = etat;
	}

	public Statut(java.lang.Long id, java.lang.String statutCode,
			java.lang.String statutLibelle, java.util.Date dateDebut,
			java.util.Date dateFin, com.rca.immatriculation.model.Etat etat) {
		this.id = id;
		this.statutCode = statutCode;
		this.statutLibelle = statutLibelle;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.etat = etat;
	}

}